# Generated by Django 3.2 on 2021-04-22 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageOTD', models.TextField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Pweight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Pheight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Saleprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Stock', models.IntegerField(null=True)),
                ('SoldCount', models.IntegerField(null=True)),
                ('Active', models.BooleanField(default=True)),
                ('UUID', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.products')),
            ],
        ),
    ]
